services:
  mysql:
    image: mysql:8.0
    container_name: sdmaa-mysql
    restart: always
    environment:
      MYSQL_DATABASE: sdmaa
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./sdmaa_back_one
    container_name: sdmaa_back
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sdmaa?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - ./sdmaa_back_one/uploads:/app/uploads

  frontend:
    build: ./sdmaa_front
    container_name: sdmaa_front
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mysql_data: