import React,{useMemo,useState} from "react";
import {ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from "react-native";
import {SafeAreaView} from "react-native-safe-area-context";
import {StatusBar} from "expo-status-bar";
import {Ionicons} from "@expo/vector-icons";
import {useNavigation} from "@react-navigation/native";
import api from "../services/api";
const C={bg:"#121212",card:"#1B1B1B",soft:"#292929",border:"#303030",text:"#FFF",muted:"#7C7C7C",red:"#E50914",green:"#1DB954"};
export default function ChangerMotDePasseScreen(){
 const navigation=useNavigation(); const [oldP,setOldP]=useState(""); const [newP,setNewP]=useState(""); const [confirm,setConfirm]=useState(""); const [saving,setSaving]=useState(false);
 const valid=useMemo(()=>oldP.length>0&&newP.length>=13&&newP===confirm&&oldP!==newP,[oldP,newP,confirm]);
 const submit=async()=>{if(!valid)return; try{setSaving(true);await api.put("/utilisateurs/me/password",{ancienMotDePasse:oldP,nouveauMotDePasse:newP,confirmationMotDePasse:confirm});Alert.alert("Mot de passe modifié","Votre mot de passe a été mis à jour.",[{text:"OK",onPress:()=>navigation.goBack()}]);}catch(e:any){Alert.alert("Erreur",e?.response?.data?.message||e?.response?.data?.error||"Impossible de modifier le mot de passe.");}finally{setSaving(false)}};
 return <SafeAreaView style={s.safe}><StatusBar style="light"/><View style={s.header}><Pressable onPress={()=>navigation.goBack()} style={s.back}><Ionicons name="arrow-back" size={22} color={C.text}/></Pressable><Text style={s.title}>Mot de passe</Text><View style={{width:42}}/></View><ScrollView contentContainerStyle={s.content}>
  <View style={s.hero}><Ionicons name="shield-checkmark-outline" size={32} color={C.text}/><Text style={s.heroTitle}>Sécurisez votre compte</Text><Text style={s.heroText}>Utilisez au moins 13 caractères et un mot de passe différent de l’ancien.</Text></View>
  <View style={s.card}><Field label="Ancien mot de passe" value={oldP} setValue={setOldP}/><Divider/><Field label="Nouveau mot de passe" value={newP} setValue={setNewP}/><Divider/><Field label="Confirmation" value={confirm} setValue={setConfirm}/></View>
  <View style={s.rules}><Rule ok={newP.length>=13} label="Au moins 13 caractères"/><Rule ok={confirm.length>0&&newP===confirm} label="Les mots de passe correspondent"/><Rule ok={oldP.length>0&&oldP!==newP} label="Différent de l’ancien"/></View>
  <Pressable disabled={!valid||saving} onPress={submit} style={[s.button,(!valid||saving)&&{opacity:.45}]}>{saving?<ActivityIndicator color={C.text}/>:<><Ionicons name="key-outline" size={20} color={C.text}/><Text style={s.buttonText}>Modifier le mot de passe</Text></>}</Pressable>
 </ScrollView></SafeAreaView>
}
function Field({label,value,setValue}:{label:string;value:string;setValue:(v:string)=>void}){const [show,setShow]=useState(false);return <View style={s.field}><View style={s.icon}><Ionicons name="lock-closed-outline" size={20} color={C.text}/></View><View style={{flex:1,marginHorizontal:13}}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={setValue} secureTextEntry={!show} autoCapitalize="none" placeholder="•••••••••••••" placeholderTextColor={C.muted} style={s.input}/></View><Pressable onPress={()=>setShow(!show)}><Ionicons name={show?"eye-off-outline":"eye-outline"} size={21} color={C.muted}/></Pressable></View>}
function Rule({ok,label}:{ok:boolean;label:string}){return <View style={s.rule}><Ionicons name={ok?"checkmark-circle":"ellipse-outline"} size={17} color={ok?C.green:C.muted}/><Text style={{color:ok?"#B3B3B3":C.muted,fontSize:12}}>{label}</Text></View>}
function Divider(){return <View style={s.divider}/>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},header:{height:64,flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:16},back:{width:42,height:42,alignItems:"center",justifyContent:"center",backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:14},title:{color:C.text,fontSize:17,fontFamily:"Inter_700Bold"},content:{paddingHorizontal:16,paddingBottom:40},hero:{alignItems:"center",padding:24,backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:28},heroTitle:{marginTop:14,color:C.text,fontSize:19,fontFamily:"Inter_700Bold"},heroText:{marginTop:8,color:C.muted,fontSize:12,lineHeight:18,textAlign:"center"},card:{overflow:"hidden",marginTop:22,backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:24},field:{minHeight:82,flexDirection:"row",alignItems:"center",paddingHorizontal:15,paddingVertical:12},icon:{width:43,height:43,alignItems:"center",justifyContent:"center",backgroundColor:C.soft,borderRadius:14},label:{color:C.muted,fontSize:10},input:{minHeight:38,color:C.text,fontSize:14},divider:{height:1,marginLeft:71,backgroundColor:C.border},rules:{gap:10,marginTop:18,padding:18,backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:20},rule:{flexDirection:"row",alignItems:"center",gap:10},button:{minHeight:56,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:10,marginTop:24,backgroundColor:C.red,borderRadius:18},buttonText:{color:C.text,fontSize:14,fontFamily:"Inter_700Bold"}});