import React from "react";
import {Alert,Linking,Pressable,ScrollView,StyleSheet,Text,View} from "react-native";
import {SafeAreaView} from "react-native-safe-area-context";
import {StatusBar} from "expo-status-bar";
import {Ionicons} from "@expo/vector-icons";
import {useNavigation} from "@react-navigation/native";
const C={bg:"#121212",card:"#1B1B1B",soft:"#292929",border:"#303030",text:"#FFF",muted:"#7C7C7C",red:"#E50914"};
export default function ConfidentialiteScreen(){const navigation=useNavigation();const contact=()=>Linking.openURL("mailto:contact@sdmaa.fr?subject=Demande concernant mes données personnelles").catch(()=>Alert.alert("Erreur","Aucune application de messagerie disponible."));
 return <SafeAreaView style={s.safe}><StatusBar style="light"/><View style={s.header}><Pressable onPress={()=>navigation.goBack()} style={s.back}><Ionicons name="arrow-back" size={22} color={C.text}/></Pressable><Text style={s.title}>Confidentialité</Text><View style={{width:42}}/></View><ScrollView contentContainerStyle={s.content}>
  <View style={s.hero}><Ionicons name="shield-checkmark-outline" size={32} color={C.text}/><Text style={s.heroTitle}>Vos données personnelles</Text><Text style={s.heroText}>Consultez les informations liées à vos données et à votre compte.</Text></View>
  <Group title="DOCUMENTS"><Row icon="document-text-outline" title="Politique de confidentialité" sub="Comment vos données sont utilisées" onPress={()=>Alert.alert("Politique de confidentialité","Le contenu complet sera ajouté prochainement.")}/><Divider/><Row icon="reader-outline" title="Conditions d’utilisation" sub="Règles d’utilisation de l’application" onPress={()=>Alert.alert("Conditions d’utilisation","Le contenu complet sera ajouté prochainement.")}/></Group>
  <Group title="MES DONNÉES"><Row icon="mail-outline" title="Contacter le club" sub="Question concernant vos données" onPress={contact}/></Group>
  <Group title="ZONE SENSIBLE"><Row icon="trash-outline" title="Supprimer mon compte" sub="Demander la suppression du compte" danger onPress={()=>Alert.alert("Supprimer mon compte","La suppression automatique n’est pas encore disponible.",[{text:"Annuler",style:"cancel"},{text:"Contacter le club",onPress:contact}])}/></Group>
  <Text style={s.note}>Certaines données peuvent devoir être conservées pour les inscriptions et les obligations administratives du club.</Text>
 </ScrollView></SafeAreaView>}
function Group({title,children}:{title:string;children:React.ReactNode}){return <View style={{marginTop:22}}><Text style={s.sectionTitle}>{title}</Text><View style={s.card}>{children}</View></View>}
function Row({icon,title,sub,onPress,danger=false}:{icon:keyof typeof Ionicons.glyphMap;title:string;sub:string;onPress:()=>void;danger?:boolean}){return <Pressable onPress={onPress} style={({pressed})=>[s.row,pressed&&{backgroundColor:C.soft}]}><View style={[s.icon,danger&&{backgroundColor:"#2B1D1F"}]}><Ionicons name={icon} size={21} color={danger?C.red:C.text}/></View><View style={{flex:1,marginHorizontal:13}}><Text style={[s.rowTitle,danger&&{color:C.red}]}>{title}</Text><Text style={s.sub}>{sub}</Text></View><Ionicons name="chevron-forward" size={20} color={C.muted}/></Pressable>}
function Divider(){return <View style={s.divider}/>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},header:{height:64,flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:16},back:{width:42,height:42,alignItems:"center",justifyContent:"center",backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:14},title:{color:C.text,fontSize:17,fontFamily:"Inter_700Bold"},content:{paddingHorizontal:16,paddingBottom:40},hero:{alignItems:"center",padding:24,backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:28},heroTitle:{marginTop:14,color:C.text,fontSize:19,fontFamily:"Inter_700Bold"},heroText:{marginTop:8,color:C.muted,fontSize:12,lineHeight:18,textAlign:"center"},sectionTitle:{marginBottom:10,marginLeft:4,color:C.muted,fontSize:10,letterSpacing:1.4,fontFamily:"Inter_700Bold"},card:{overflow:"hidden",backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:24},row:{minHeight:84,flexDirection:"row",alignItems:"center",paddingHorizontal:15,paddingVertical:12},icon:{width:43,height:43,alignItems:"center",justifyContent:"center",backgroundColor:C.soft,borderRadius:14},rowTitle:{color:C.text,fontSize:14,fontFamily:"Inter_600SemiBold"},sub:{marginTop:4,color:C.muted,fontSize:11,lineHeight:16},divider:{height:1,marginLeft:71,backgroundColor:C.border},note:{marginTop:12,paddingHorizontal:5,color:C.muted,fontSize:10,lineHeight:16}});