import React,{useEffect,useState} from "react";
import {ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Switch,Text,View} from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import {SafeAreaView} from "react-native-safe-area-context";
import {StatusBar} from "expo-status-bar";
import {Ionicons} from "@expo/vector-icons";
import {useNavigation} from "@react-navigation/native";
const KEY="sdmaa_notification_preferences";
const C={bg:"#121212",card:"#1B1B1B",soft:"#292929",border:"#303030",text:"#FFF",muted:"#7C7C7C",red:"#E50914"};
const defaults={generales:true,annonces:true,activites:true,competitions:true,stages:true,inscriptions:true,equipements:false};
type Pref=typeof defaults;
export default function NotificationsParametresScreen(){const navigation=useNavigation();const [p,setP]=useState<Pref>(defaults);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);
 useEffect(()=>{AsyncStorage.getItem(KEY).then(v=>v&&setP({...defaults,...JSON.parse(v)})).catch(()=>Alert.alert("Erreur","Impossible de charger les préférences.")).finally(()=>setLoading(false))},[]);
 const update=(k:keyof Pref,v:boolean)=>setP(c=>k==="generales"?{...c,generales:v,annonces:v?c.annonces:false,activites:v?c.activites:false,competitions:v?c.competitions:false,stages:v?c.stages:false,inscriptions:v?c.inscriptions:false,equipements:v?c.equipements:false}:{...c,[k]:v});
 const save=async()=>{try{setSaving(true);await AsyncStorage.setItem(KEY,JSON.stringify(p));Alert.alert("Préférences enregistrées","Vos choix ont été sauvegardés.",[{text:"OK",onPress:()=>navigation.goBack()}])}finally{setSaving(false)}};
 if(loading)return <SafeAreaView style={s.safe}><View style={s.load}><ActivityIndicator color={C.text}/><Text style={s.muted}>Chargement...</Text></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><StatusBar style="light"/><View style={s.header}><Pressable onPress={()=>navigation.goBack()} style={s.back}><Ionicons name="arrow-back" size={22} color={C.text}/></Pressable><Text style={s.title}>Notifications</Text><View style={{width:42}}/></View><ScrollView contentContainerStyle={s.content}>
  <Group title="GÉNÉRAL"><Row icon="notifications-outline" title="Toutes les notifications" sub="Activer ou désactiver toutes les alertes" value={p.generales} onChange={v=>update("generales",v)}/></Group>
  <Group title="CLUB ET ACTIVITÉS"><Row icon="megaphone-outline" title="Annonces du club" sub="Informations et actualités" value={p.annonces} disabled={!p.generales} onChange={v=>update("annonces",v)}/><Divider/><Row icon="calendar-outline" title="Nouvelles activités" sub="Création et modification d’activités" value={p.activites} disabled={!p.generales} onChange={v=>update("activites",v)}/><Divider/><Row icon="trophy-outline" title="Compétitions" sub="Dates et inscriptions" value={p.competitions} disabled={!p.generales} onChange={v=>update("competitions",v)}/><Divider/><Row icon="fitness-outline" title="Stages" sub="Stages et entraînements spéciaux" value={p.stages} disabled={!p.generales} onChange={v=>update("stages",v)}/></Group>
  <Group title="COMPTE"><Row icon="checkmark-circle-outline" title="Rappels d’inscription" sub="Demandes et validations" value={p.inscriptions} disabled={!p.generales} onChange={v=>update("inscriptions",v)}/><Divider/><Row icon="bag-handle-outline" title="Équipements" sub="Commandes et disponibilités" value={p.equipements} disabled={!p.generales} onChange={v=>update("equipements",v)}/></Group>
  <Pressable onPress={save} disabled={saving} style={[s.button,saving&&{opacity:.5}]}>{saving?<ActivityIndicator color={C.text}/>:<Text style={s.buttonText}>Enregistrer</Text>}</Pressable>
 </ScrollView></SafeAreaView>}
function Group({title,children}:{title:string;children:React.ReactNode}){return <View style={{marginTop:22}}><Text style={s.sectionTitle}>{title}</Text><View style={s.card}>{children}</View></View>}
function Row({icon,title,sub,value,onChange,disabled=false}:{icon:keyof typeof Ionicons.glyphMap;title:string;sub:string;value:boolean;onChange:(v:boolean)=>void;disabled?:boolean}){return <View style={[s.row,disabled&&{opacity:.45}]}><View style={s.icon}><Ionicons name={icon} size={21} color={C.text}/></View><View style={{flex:1,marginHorizontal:13}}><Text style={s.rowTitle}>{title}</Text><Text style={s.sub}>{sub}</Text></View><Switch value={value} disabled={disabled} onValueChange={onChange} trackColor={{false:"#4A4A4A",true:"#9D1B22"}} thumbColor={value?C.red:"#D7D7D7"}/></View>}
function Divider(){return <View style={s.divider}/>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},header:{height:64,flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:16},back:{width:42,height:42,alignItems:"center",justifyContent:"center",backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:14},title:{color:C.text,fontSize:17,fontFamily:"Inter_700Bold"},content:{paddingHorizontal:16,paddingBottom:40},sectionTitle:{marginBottom:10,marginLeft:4,color:C.muted,fontSize:10,letterSpacing:1.4,fontFamily:"Inter_700Bold"},card:{overflow:"hidden",backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:24},row:{minHeight:86,flexDirection:"row",alignItems:"center",paddingHorizontal:15,paddingVertical:12},icon:{width:43,height:43,alignItems:"center",justifyContent:"center",backgroundColor:C.soft,borderRadius:14},rowTitle:{color:C.text,fontSize:14,fontFamily:"Inter_600SemiBold"},sub:{marginTop:4,color:C.muted,fontSize:11,lineHeight:16},divider:{height:1,marginLeft:71,backgroundColor:C.border},button:{minHeight:56,alignItems:"center",justifyContent:"center",marginTop:26,backgroundColor:C.red,borderRadius:18},buttonText:{color:C.text,fontSize:14,fontFamily:"Inter_700Bold"},load:{flex:1,alignItems:"center",justifyContent:"center"},muted:{marginTop:12,color:C.muted}});